language: php

php:
  - 7.2

install:
  - composer install

script:
  - composer lint
  - composer test

after_script:
  - composer test-report

notifications:
  email: false

cache:
  directories:
    - $HOME/.composer/cache
