version: '3'

services:

  mysql:
    image: mysql:5
    ports:
      - "3306:3306"
    volumes:
       - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password

  wordpress:
    image: wordpress:php7.2-fpm
    depends_on:
      - mysql
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ".:/var/www/html/wp-content/plugins/block-context"
    restart: always
    environment:
      WORDPRESS_DEBUG: 1
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: password

volumes:
    db_data: {}