name: Test

on:
  push:
  workflow_call:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  WP_ENV_HOME: .cache/wp-env
  COMPOSER_CACHE_DIR: .cache/composer

jobs:

  test:
    name: Lint and Test
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      pull-requests: write
      checks: write
    steps:
      - uses: actions/checkout@v7

      - uses: actions/setup-node@v7
        with:
          node-version-file: .nvmrc
          cache: npm

      - uses: actions/cache@v6
        with:
          path: .cache
          key: ${{ runner.os }}-cache-${{ hashFiles( 'composer.lock', 'package-lock.json', '.wp-env.json' ) }}
          restore-keys: ${{ runner.os }}-cache-

      - name: Setup PHP and Composer
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          tools: composer

      - name: Install tooling
        run: npm install

      - name: Install PHP tooling
        run: composer install

      - name: Start the environment
        run: npm run start

      - name: Install PHP dependencies
        run: npm run cli -- composer install

      - name: Lint
        run: npm run lint

      - name: Test
        run: npm run test

      - name: Build
        run: npm run build
