name: Test

on:
  push:
  workflow_call:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  WP_ENV_HOME: .cache/wp-env

jobs:

  test:
    name: Lint and Test
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      pull-requests: write
      checks: write
    steps:
      - uses: actions/checkout@v6

      - name: Setup NodeJS
        uses: actions/setup-node@v6
        with:
          node-version-file: .nvmrc
          cache: npm

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          tools: composer:v2

      - name: Get Composer cache directory
        id: composer-cache
        run: echo "dir=$(composer config cache-files-dir)" >> "$GITHUB_OUTPUT"

      - name: Setup cache for dependencies
        uses: actions/cache@v5
        with:
          path: |
            ${{ steps.composer-cache.outputs.dir }}
            .cache
          key: ${{ runner.os }}-cache-${{ hashFiles( 'composer.lock', 'package-lock.json', '.wp-env.json' ) }}
          restore-keys: ${{ runner.os }}-cache-

      - name: Install tooling
        run: npm install

      - name: Install PHP dependencies
        run: composer install

      - name: Start the environment
        run: npm run start

      - name: Lint
        run: npm run lint

      - name: Test
        run: npm run test

      - name: Build
        run: npm run build

      - name: Report code coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: tests/coverage/phpunit-cobertura.xml
          disable_telem: true
